name: Run Mabl Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Functional test deployment (mabl)
        id: mabl-test-deployment
        uses: mablhq/github-run-tests-action@v1
        env:
          # Use the secret you created in your repo settings
          MABL_API_KEY: ${{ secrets.API_Key }}     # <-- you can rename secret to MABL_API_KEY if preferred
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          application-id: "wX6fU33nyZCxJUl21wXyXw-a"
          environment-id: "tDbAqTooLcWDcGoX8lefEA-e"
